default_language_version:
  python: python3.7

default_stages: [commit, push]
fail_fast: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: ['--autofix']
  - id: trailing-whitespace

- repo: https://github.com/annarailton/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports']

# Format docstrings
- repo: https://github.com/annarailton/docformatter
  rev: 23d96adf42b094f1874ce9bb2815c5d35b8f2dba
  hooks:
  - id: docformatter

# Reformat all the things
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf

# Run flake8 last so you don't pick up the stuff you just fixed
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: flake8
    additional_dependencies: [
          'flake8-blind-except',
          'flake8-comprehensions',
          'flake8-deprecated',
          'flake8-mutable',
          'flake8-pep3101',
          'flake8-quotes',
          'flake8-string-format',
          'flake8-tidy-imports',
          'flake8-todo',
          ]
    args: ['--ignore=P1,P2,E251,W504,E50,E111,E114,E121,E131']  # valid E251 caught by yapf

# Lint any markdown (requires Ruby >=2.4)
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.8.0
  hooks:
  - id: markdownlint
    name: Markdownlint
    description: Run markdownlint on your Markdown files
    entry: mdl
    language: ruby
    files: \.(md|mdown|markdown)$
